### ISSUE TITLE
python 3.6 support?

### ISSUE THREAD

**Issue by caseyjlaw** [astro-datalab/datalab#49]
I have an environment built around Python 3.6 and would like to install `datalab` there. Using the pip installation instructions listed in this repo, I get an error when installing `asdf_transform_schemas`. E.g.,
```
pip install --ignore-installed --no-cache-dir astro-datalab
...
ERROR: Could not find a version that satisfies the requirement asdf-coordinates-schemas (from asdf-astropy>=0.2.0->gwcs!=0.16.0->specutils->astro-datalab) (from versions: none)
ERROR: No matching distribution found for asdf-coordinates-schemas (from asdf-astropy>=0.2.0->gwcs!=0.16.0->specutils->astro-datalab)
```

I can't find much documentation about that requirement, but nothing explicitly mentions lack of Python 3.6 support. Is that version supported?

**Comment by mjfitzpatrick** [comment]
The asdf-coordinates-schema package (which is a dependency of specutils and not used directly) explicitly has a pyton>3.7 requirement in its package setup.cfg file.  If you're not planning to use ASDF files, one workaround might be to download the package from Git directly (https://github.com/asdf-format/asdf-coordinates-schemas), edit the 'setup.cfg' file to modify the 3.7 requirement and then install it with "python setup.py install".  The theory being that if the package is seen as already installed in your environment it will be skipped when doing the pip install of 'datalab'.  Hope this helps.

**Comment by caseyjlaw** [comment]
Ok, thanks for the quick reply. That worked for me.
