### ISSUE TITLE
`--ignore-installed` can break existing conda environment

### ISSUE THREAD

**Issue by G-Francio** [astro-datalab/datalab#76]
Minor issue, but this broke my conda environment as pip pulled `numpy=2.1.1`, which was incompatible with another package.

The ReadMe suggests to install the package using `pip` and the `--ignore-installed` flag. However, if this is is used in a conda envoronment, problems might arise as `pip` will ignore all currently installed packages by conda, and will (or could) overwrite installed version with non-compatible ones or just install a second version leading to a complete import mess.

Unless there is a specific reason I am not aware of, It would be helpful to change the flag to `--force-reinstall`, or at least include a warning to first run `pip` with both the `--ignore-installed` and the `--dry-run` flags to inspect what would happen upon installation.

Cheers, and thanks for the package!

**Comment by chaduhduh** [comment]
Hey @G-Francio,

I had a look and updated the instructions within the README accordingly. Thank you for bringing this to our attention and for your patience. This will likely save people time and frustration in the future. 

**Note:** I wasn't able to fully recreate the issue except when using specific versions of our package (some older versions had loose restrictions for numpy) but either way that step in the instructions was out of date. If you continue to encounter problems feel free to open a new issue and we can provide further assistance.
