### ISSUE TITLE
Update requirements.txt with numpy 1.26.1

### ISSUE THREAD

**Issue by jacquesalice** [astro-datalab/datalab#77]
numpy==1.26.1 was installed in the datalab package on August 1, 2024. The requirements.txt doc needs to be updated for this version of numpy, from:

`numpy>=1.23.5,<1.24.0; python_version >= "3.10" and python_version < "3.12"`
`numpy>=1.23.4,<1.24.0; python_version == "3.9"`

to:

`numpy>=1.23.5,<=1.26.1; python_version >= "3.10" and python_version < "3.12"`
`numpy>=1.23.4,<=1.26.1; python_version == "3.9"`

Otherwise, the following warning message appears when trying to import the SparclClient:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
astro-datalab 2.23.1 requires numpy<1.24.0,>=1.23.5; python_version >= "3.10" and python_version < "3.12", but you have numpy 1.26.1 which is incompatible.`

@chaduhduh do you think you could take care of this?

**Comment by chaduhduh** [comment]
Hey @jacquesalice, I will have a look at this. Is this for a development version of SparclClient or is this impacting the latest release? Let me know so I can prioritize accordingly.

**Comment by jacquesalice** [comment]
@chaduhduh it's impacting the latest release

**Comment by chaduhduh** [comment]
Resolved in v2.24.0
